/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gui;

/**
 *
 * @author jmloaiza
 */
public class panPalette extends javax.swing.JPanel {

    StartWindow _parent;
    /**
     * Creates new form panPalette
     */
    public panPalette(StartWindow pWindow) {
        initComponents();
        _parent = pWindow;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bttClose = new javax.swing.JLabel();
        bttFinalState = new javax.swing.JLabel();
        bttInitState = new javax.swing.JLabel();
        bttState = new javax.swing.JLabel();
        bkg = new javax.swing.JLabel();

        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(285, 419));
        setLayout(null);

        bttClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images/bttClose.png"))); // NOI18N
        bttClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bttClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bttCloseMouseClicked(evt);
            }
        });
        add(bttClose);
        bttClose.setBounds(258, 9, 16, 15);

        bttFinalState.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images/bttFinalState.png"))); // NOI18N
        bttFinalState.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        add(bttFinalState);
        bttFinalState.setBounds(54, 202, 58, 58);

        bttInitState.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images/bttInitState.png"))); // NOI18N
        bttInitState.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        add(bttInitState);
        bttInitState.setBounds(172, 85, 53, 36);

        bttState.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images/bttState.png"))); // NOI18N
        bttState.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        bttState.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                bttStateMouseReleased(evt);
            }
        });
        bttState.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                bttStateMouseDragged(evt);
            }
        });
        add(bttState);
        bttState.setBounds(54, 76, 58, 58);

        bkg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images/bkgPalette.png"))); // NOI18N
        add(bkg);
        bkg.setBounds(0, 0, 285, 419);
    }// </editor-fold>//GEN-END:initComponents

    private void bttCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttCloseMouseClicked
        setVisible(false);
        setEnabled(false);
        _parent.onEditMode(false);
    }//GEN-LAST:event_bttCloseMouseClicked

    private void bttStateMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttStateMouseDragged
        System.out.println("drag: " + evt.getLocationOnScreen().toString());
    }//GEN-LAST:event_bttStateMouseDragged

    private void bttStateMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttStateMouseReleased
        System.out.println("relase: " + evt.getLocationOnScreen().toString());
    }//GEN-LAST:event_bttStateMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bkg;
    private javax.swing.JLabel bttClose;
    private javax.swing.JLabel bttFinalState;
    private javax.swing.JLabel bttInitState;
    private javax.swing.JLabel bttState;
    // End of variables declaration//GEN-END:variables
}
